// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_LQ5k1LziOJ4oLNGEpi4P6I-TLUKjxfM',
    appId: '1:142397868935:web:82d61794bde4478eaea122',
    messagingSenderId: '142397868935',
    projectId: 'ecommerce-be423',
    authDomain: 'ecommerce-be423.firebaseapp.com',
    storageBucket: 'ecommerce-be423.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyMHdcOOZ15RkABxsOVENvXGu7S7_Exw',
    appId: '1:142397868935:android:9585d83375a72f2faea122',
    messagingSenderId: '142397868935',
    projectId: 'ecommerce-be423',
    storageBucket: 'ecommerce-be423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa662B7wAfOd2VGnwviIci4v9za9HldCM',
    appId: '1:142397868935:ios:ed39a176367b9cfeaea122',
    messagingSenderId: '142397868935',
    projectId: 'ecommerce-be423',
    storageBucket: 'ecommerce-be423.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa662B7wAfOd2VGnwviIci4v9za9HldCM',
    appId: '1:142397868935:ios:bce464244fd6ebacaea122',
    messagingSenderId: '142397868935',
    projectId: 'ecommerce-be423',
    storageBucket: 'ecommerce-be423.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
